"use client";

import AddCardModal from "@/components/modal/AddCardModal";
import AddRecipientsModal from "@/components/modal/AddRecipientsModal";
import CardModal from "@/components/modal/CardModal";
import CongratulationsModal from "@/components/modal/CongratulationsModal";
import PurchasedModal from "@/components/modal/PurchasedModal";
import RecipientsModal from "@/components/modal/RecipientsModal";
import TransactionModal from "@/components/modal/TransactionModal";
import TransferModal from "@/components/modal/TransferModal";
import NavBar from "@/components/navBar/NavBar";
import Preloader from "@/components/preloader/Preloader";
import { PaylioProvider } from "@/context/context";
import { useEffect } from "react";

// main style
import Footer from "@/components/footer/Footer";
import "../styles/globals.scss";

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  return (
    <html lang="en">
      <head>
        <title>
          Paylio - Money Transfer and Online Payments Dashboard React Next JS
          Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </head>
      <body>
        <PaylioProvider>
          {/* Preloader */}
          <Preloader />

          {/* Recipients Modal    */}
          <RecipientsModal />

          {/* Transfer Modal */}
          <TransferModal />

          {/* Purchased Modal */}
          <PurchasedModal />

          {/* Congratulations Modal */}
          <CongratulationsModal />

          {/* Add Card Modal */}
          <AddCardModal />

          {/* Card Modal */}
          <CardModal />

          {/* Transaction Modal */}
          <TransactionModal />

          {/* AddRecipients Modal */}
          <AddRecipientsModal />

          {/* NavBar */}
          <NavBar />

          {children}
          <Footer />
        </PaylioProvider>
      </body>
    </html>
  );
}
